### ISSUE TITLE
ffmpeg is installed but ytmdl can't find it.

### ISSUE THREAD

**Issue by Syndrome1986** [deepjyoti30/ytmdl#78]
Windows 10
Python 3.8
ytmdl will start and attempt to search for a song then drops 
==> ffmpeg is not installed. Please install it!
It is likely something simple that I am just not seeing. 

`PS C:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\Scripts> pip show ffmpeg
Name: ffmpeg
Version: 1.4
Summary: ffmpeg python package url [https://github.com/jiashaokun/ffmpeg]
Home-page: https://github.com/jiashaokun/ffmpeg
Author: SkeyJIA
Author-email: 363604236@qq.com
License: MIT Licence
Location: c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages
Requires:
Required-by:`

**Comment by deepjyoti30** [comment]
Hey @Syndrome1986 Can you please tell me if you're using in on Windows WSL or just Windows. I'm aware that it has issues on pure Windows but some users have it running on Windows WSL.

**Comment by Syndrome1986** [comment]
I am attempting to run it in Windows without wsl. I can try it again with wsl. I was hoping to get it working in just windows for a less technical friend.

**Comment by deepjyoti30** [comment]
If you want a temporary fix, you can comment out the lines checking for ffmpeg.
 
Those lines would be in the ```ytmdl``` file in the ```bin/``` directory.

If you are able to fix the bugs and make it support Windows, I'd be glad to merge the PR's, so feel free to do that. Also, you can share your logs here (if you want to) and I can make the fixes.

**Comment by Syndrome1986** [comment]
A bit more info. I think it is an issue with how sys.path is being handled. When I start python and import os and import sys I get two different locations for site-packages. It looks like my python is trying to run from C:\\Program Files\\WindowsApps\\ but pip is working from C:\\Users\\User\\AppData\\Local\\Packages\\. After checking sys.prefix it looks like python only knows about the WindowsApps install. 

This is likely related to using the App Store version of Python. I did add the \\local\\packages\\ folder to the Windows System Env $PATH but it does not seem to make a difference. 

Full sys.path output:
` ''
'C:\\Users\\User\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages'
'C:\\Users\\User\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0'
 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0'
 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\\lib\\site-packages'
 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\\python38.zip'
 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\\DLLs'
 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\\lib'
`

**Comment by Syndrome1986** [comment]
> If you want a temporary fix, you can comment out the lines checking for ffmpeg.

I did try this just now and am getting the same error as in issue #75

**Comment by deepjyoti30** [comment]
@Syndrome1986 Thanks for reporting that. As the logs in #75 suggest the error is probably thrown by ```youtube-dl```. I'll have to do some tests myself to fix the bug. Some changes in the source perhaps.

**Comment by Syndrome1986** [comment]
If you need testing done let me know. I am happy to try it.

**Comment by deepjyoti30** [comment]
@Syndrome1986 I figured out the issue you were facing. The ```stty``` error is because when the download is about to start, it does some checks in order to get the terminal length and in Windows, that fallbacks to ```stty``` to get the length and that's where the issue is.

I'll make some changes to fix that and report back here.

**Comment by deepjyoti30** [comment]
@Syndrome1986 Can you please try with the latest commit from the windows branch?

I have made some changes that should fix the ```stty``` issue.

**Comment by Syndrome1986** [comment]
I removed Python fully from the machine and purged all python related folders. I reinstalled 3.8 via installer rather than windows store version. I have attached my console output from where I updated pip to where I was able to install and test the newest version. Still getting the issue where it says ffmpeg is not installed. I will test again after commenting out the part of ytmdl that checks for ffmpeg.
[ytmdl console.txt](https://github.com/deepjyoti30/ytmdl/files/4808728/ytmdl.console.txt)

**Comment by Syndrome1986** [comment]
Commenting out the check for ffmpeg now leaves me with an error stating youtube-dl is not installed. Commenting out the check for youtube-dl brings me back to the stty error.

**Comment by deepjyoti30** [comment]
@Syndrome1986 Hey there. Did you try the windows branch??

I had commented out the ffmpeg part in that one and it should probabaly not throw any issues. Also you will have to install the windows branch manually by cloning the repo and then running ```python setup.py install``` in the root directory.

**Comment by manthanabc** [comment]
> @Syndrome1986 Hey there. Did you try the windows branch??
> 
> I had commented out the ffmpeg part in that one and it should probabaly not throw any issues. Also you will have to install the windows branch manually by cloning the repo and then running `python setup.py install` in the root directory.
> 
> Update: Just checked the txt file you included. The issue is because you installed the latest release.
> 
> Here's how to get the latest working build from the windows branch.
> 
> * Uninstall the previous installed build since it was installed with pip, it might create issues.
> * Go to the windows branch and download the zip. (Since you're in Windows I'm assuming you're not using git so I'm not gonna ask you to clone and then checkout)
> * Unzip the downloaded zip and open cmd on the root directory.
> * Run `python3 setup.py install`.
> 
> Once this is done, you can try running ytmdl. The ffmpeg issue should not occur and you should get to the downloading the song
> part (at least) and the `stty` error won't occur.

Ahh sorry I know this sounds a bit dumb but I think I need to verify before trying does root directory means the... Scripts\ directry

**Comment by deepjyoti30** [comment]
@manthanabc There probably won't be any scripts directory. Just extract the zip file and go to the extracted folders you'll see a folder named ```ytmdl```.

Move inside this folder and open a cmd prompt as administrator.

Type the following command and run in the cmd

```py3 setup.py install```

Once that's done, ytmdl will be installed. Try running ytmdl and add the ```--level DEBUG``` and then you can reply here with the output if you face any bugs.

**Comment by manthanabc** [comment]
![error](https://user-images.githubusercontent.com/48511543/86436088-2c1dae80-bd1f-11ea-9afd-dd17338e1c6a.PNG)
this is what shous if tried manuall install pip works but ffmpeg error

**Comment by deepjyoti30** [comment]
@manthanabc Do you have ```ffmpeg``` installed in your system??

If ```ytmdl``` is installed, you can try running ytmdl by running the script present in the ```bin/``` directory.

You can do ```py3 bin\ytmdl```

**Comment by manthanabc** [comment]
![error2](https://user-images.githubusercontent.com/48511543/86442144-f252a500-bd2a-11ea-977b-2db5bc7b63ee.PNG)
i really dont know what to do

**Comment by deepjyoti30** [comment]
@manthanabc Seems like this is the issue itself. Since another user reported the same issue.

**Comment by manthanabc** [comment]
I am still waiting for fix tho :/

**Comment by deepjyoti30** [comment]
@manthanabc Hey sorry for the late reply. It seems like you're facing this issue on Windows? That's one of the reasons I'm unable to fix it. I don't have access to an windows machine and thus I cannot add support for Windows to `ytmdl`.

Even though there's the Windows branch where I made changes based on user input, it is normal to face some unexpected issues that are to be fixed later but I cannot fix the issue without properly understanding why it is happening, which again brings us back to the point of testing on Windows.
